# Generated by Django 2.2.5 on 2020-05-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200426_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_name',
            field=models.CharField(blank=True, db_index=True, max_length=25),
        ),
    ]
