# Generated by Django 2.2.5 on 2020-05-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
