# Generated by Django 2.2.5 on 2020-06-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200519_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(db_index=True, default='Add your information', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, db_index=True, default='Add your name', max_length=20),
        ),
    ]
