# Generated by Django 2.2.5 on 2020-06-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200605_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(db_index=True, default='profile/default.jpg', upload_to='profile/'),
        ),
    ]
